apiVersion: apps/v1
kind: Deployment
metadata:
    name: jenkins-k8s
    labels:
        app: jenkins-k8s
spec:
    replicas: 1
    selector:
        matchLabels:
            app: jenkins-k8s
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: jenkins-k8s
                tier: jenkins-k8s
        spec:
            containers:
            - name: jenkins-k8s
              image: ivelia/jenkins-k8s
              imagePullPolicy: Always
              ports:
              - containerPort: 5000
                name: jenkins-k8s