apiVersion: apps/v1
kind: Deployment
metadata:
    name: jenkinskubernetesdeployment
    labels:
        app: jenkinskubernetesdeployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: jenkinskubernetesdeployment
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: jenkinskubernetesdeployment
                tier: jenkinskubernetesdeployment
        spec:
            containers:
            - name: jenkinskubernetesdeployment
              image: ivelia/jenkinskubernetesdeployment
              imagePullPolicy: Always
              ports:
              - containerPort: 5000
                name: jenkinskubernetesdeployment