apiVersion: v1
kind: Service
metadata:
    name: jenkinskubernetesdeployment
    labels:
        app: jenkinskubernetesdeployment
spec:
    ports:
    - port: 5000
      targetPort: 5000
    selector:
      app: jenkinskubernetesdeployment
      tier: jenkinskubernetesdeployment
    type: LoadBalancer
