apiVersion: v1
kind: Service
metadata:
    name: jenkins-k8s
    labels:
        app: jenkins-k8s
spec:
    ports:
    - port: 5000
      targetPort: 5000
    selector:
      app: jenkins-k8s
      tier: jenkins-k8s
    type: LoadBalancer
